### ISSUE TITLE
test negative cases for backup/restore process to define better messaging

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#10]
As I see now it is impossible to do backup for non-existing container, i.e. it might be obligatory started and stopped (not removed!).
The similar use-cases for restore - it can be done over the started/stopped existing container.
Also during restore we might verify prleiminary that sonarqube.tar.gz exists etc.
How about automatic restart after restore...

So need to define different positive and negative scenarios for testing new funcitonality

**Comment by vdelendik** [comment]
closde to move onto the "Ready For QA" state

**Comment by ghost** [comment]
I have issues with backup on qps-infra develop now.

**Comment by ghost** [comment]
<img width="662" alt="Screen Shot 2020-08-11 at 6 23 24 PM" src="https://user-images.githubusercontent.com/32964663/89916133-ebf3fa80-dbff-11ea-8a8f-91699914e718.png">

**Comment by vdelendik** [comment]
test one more time please

**Comment by ghost** [comment]
Need to fix: Change messages for the following cases 
In the case1
1. after ./zebrunner.sh down
2. run ./zebrunner.sh backup or ./zebrunner.sh restore
Actual result:
Message:
TODO: implement logic
TODO: implement logic
Unable to find image 'zebrunner/sonarqube:1.0' locally
1.0: Pulling from zebrunner/sonarqube
Digest: sha256:c0be96e3f1497bb6da2f92ebb5d7ab85ce3e64f82cef366f140f06cfd9a4e79c
Status: Image is up to date for zebrunner/sonarqube:1.0
docker: Error response from daemon: No such container: sonarqube.
See 'docker run --help'.
TODO: implement logic
Expected: Message should be more user friendly e.g. "docker: Error response from daemon: No such container: sonarqube.
See 'docker run --help'.

In the case2
1. after ./zebrunner.sh shutdown
2. run ./zebrunner.sh backup or ./zebrunner.sh restore
Actual result:
Message:
TODO: implement logic
TODO: implement logic
Unable to find image 'zebrunner/sonarqube:1.0' locally
1.0: Pulling from zebrunner/sonarqube
Digest: sha256:c0be96e3f1497bb6da2f92ebb5d7ab85ce3e64f82cef366f140f06cfd9a4e79c
Status: Image is up to date for zebrunner/sonarqube:1.0
docker: Error response from daemon: No such container: sonarqube.
See 'docker run --help'.
TODO: implement logic
Expected: Message should be more user friendly e.g. "docker: Error response from daemon: No such container: sonarqube.
See 'docker run --help'.

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/sonarqube/pull/19

**Comment by ilya-varchenya** [comment]
### Test scenario:

Prerequisites:

- Clone [sonarqube](https://github.com/zebrunner/sonarqube) repo to your machine
- Change branch to **develop**: git checkout develop
- Change tag of sonarqube container in .env file (ping me for help: I'll tell you how to create correct image)

Test steps:
1. run sonarqube container `./zebrunner.sh start`
2. `./zebrunner.sh backup`
3. Check logs that container was backupped
4. `./zebrunner.sh stop`
5. `./zebrunner.sh backup`
6. Check logs that container was backupped
7. `./zebrunner.sh down`
8. `./zebrunner.sh backup`
9. Check that logs has message 
> 
_WARNING! Impossible backup sonarqube container!_
> 
10. `./zebrunner.sh down`
11. `./zebrunner.sh backup`
12. Check that logs has message 
> 
_WARNING! Impossible backup sonarqube container!_
> 

The same scenario for **restore** (write `restore` instead `backup`)

**Comment by dhreben** [comment]
Fixed
