### ISSUE TITLE
add explanation about start/stop/restart/down/shutdown/back and restore methods

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#11]
For ./zebrunner.sh --help" we have to provide more information about each operation in details.

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/sonarqube/pull/15

**Comment by ilya-varchenya** [comment]
Test scenario:
(Stop qps-infra if you will test on machine, that has it)
1. clone sonarqube repo into your AWS instance
2. run `./zebrunner.sh -h`
3. check functionality of zebrunner.sh with flags that are specified in `help`
3.1 **start** - container should start
3.2 **stop** - container should stop and keep
3.3 **restart** - container should restart
3.4 **down** - container should stop and remove
3.5 **shutdown** - container should stop and remove, volumes should clear
3.6 **backup** - container should backup information into backup folder
3.7 **restore** - container should restore information from backup folder
4. Check that information could be backuped
4.1 Start sonarqube `./zebrunner.sh start`
4.2 Open in your browser <your_hostname>:9000/sonarqube
4.2 Login with demo credentials (admin/admin)
4.3 Create some sample project
4.4 Run `./zebrunner.sh backup`
4.5 Delete container and it's volumes `./zebrunner.sh shutdown`
4.6 Start new container `./zebrunner.sh start`
4.7 Open in your browser <your_hostname>:9000/sonarqube
4.8 Login with demo credentials (admin/admin)
4.10 Check that there's no any project
4.11 Restore container's volume data `./zebrunner.sh restore`
4.12 Restart container `./zebrunner.sh restart`
4.13 Open in your browser <your_hostname>:9000/sonarqube
4.14 Check that your project has been returned

**Comment by ghost** [comment]
After start ./zebrunner.sh -h
Actual result:
Usage: ./zebrunner-server setup|start|stop|restart|down|shutdown|backup|restore
@ilya-varchenya  is it expected result for help
and after ./zebrunner.sh shutdown need to run ./zebrunner.sh setup

Issue:
Expected: 4.14 Check that your project has been returned
Actual result: 4.14 project has not been returned

**Comment by vdelendik** [comment]
fixed

**Comment by ghost** [comment]
Will be created a new ticket for Projects page. Previous results are empty.
