### ISSUE TITLE
publish common information about this repo 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#12]
Need more details/explanations why do we recommend to use sonar. 
What's languages/version we already support. 
Provide link to the qps-infra configuration steps: https://qaprosoft.github.io/qps-infra/config-guide/#sonarqube-setup

**Comment by ghost** [comment]
SonarQube (formerly Sonar) is an open-source platform for continuous inspection of code quality to perform automatic reviews with static analysis of code to detect bugs, code smells, and security vulnerabilities on 20+ programming languages. SonarQube offers reports on duplicated code, coding standards, unit tests, code coverage, code complexity, comments, bugs, and security vulnerabilities.
It can record metrics history and provides evolution graphs. Provides fully automated analysis and integration with Maven, Ant, Gradle, MSBuild and continuous integration tools (Atlassian Bamboo, Jenkins, Hudson, etc.).

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/sonarqube/blob/develop/README.md

**Comment by dhreben** [comment]
Verified
