### ISSUE TITLE
investigate possibility to add "status" operation

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#14]
./zebrunner.sh status

it supposed to verify if image/container exists and it's status: up&running, stopped or removed.
Also based on volumes detection we can say if any data persisted at all

**Comment by ilya-varchenya** [comment]
https://github.com/zebrunner/sonarqube/pull/17

**Comment by ilya-varchenya** [comment]
Test scenario:
1. run container with `./zebrunner.sh start`
2. Check status of this container with `docker ps -a | grep sonarqube`
3. Check status of this container with `./zebrunner.sh status`
![image](https://user-images.githubusercontent.com/44428408/89634367-eae46580-d8ad-11ea-95aa-f09dc8221086.png)

4. Results of second and third steps should be simmilar

**Comment by ghost** [comment]
Tested on qps-infra develop. It is not ready yet
Welcome to Zebrunner Sonarqube (Community Edition)
Usage: ./zebrunner.sh start|stop|restart|down|shutdown|backup|restore

**Comment by ghost** [comment]
Reverified on sonarqube master. Done.
