### ISSUE TITLE
implement healthcheck for sonarqube container

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#24]
subj

**Comment by vdelendik** [comment]
feature implemented: https://github.com/zebrunner/sonarqube/pull/23/files#diff-769a9fbec2bab5745575dee73cffa3f1R18
`./zebrunner.sh status`

above command should return valid status of the service. testing should include execution of the command when:
1) everything is ok, service up&running
2) sonarqube docker container stopped
3) sonarqube docker container stopped and removed

**Comment by ghost** [comment]
Tested on dev. branch:
In the case when sonarqube is runing
Go to sonarqube folder and run ./zebrunner.sh status
Actual result:WARNING! There's no container sonarqube

**Comment by ghost** [comment]
Reverified. Issue is not fixed.

**Comment by vdelendik** [comment]
done. the root cause of the problem: 1.0 version of sonarqube was used in zebrunner branch: develop.

```
./zebrunner.sh start
./zebrunner.sh status
-> sonarqube is starting
# wait 1-2 min 
./zebrunner.sh status
-> sonarqube is healthy
./zebrunner.sh stop
-> Stopping sonarqube ... done
./zebrunner.sh status
-> sonarqube is unhealthy
./zebrunner.sh down
Removing sonarqube ... done
Network infra is external, skipping
./zebrunner.sh status

->      WARNING! There's no container sonarqube
```

**Comment by ghost** [comment]
Reverified on release build.

**Comment by ghost** [comment]
Verified on dev. env. Done.
