### ISSUE TITLE
migrate to 1.6.0 community branch plugin

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#29]
new 1.5.0 community branch plugin released:
https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/tag/1.5.0

let's try to move onto this version and if possible upgrade sonarqube instance to 8.4 as well

**Comment by vdelendik** [comment]
1.6.0 is available

**Comment by vdelendik** [comment]
https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/1
aboe ticket is fixed in 1.4.0+ so current 1.3.2 has exactly the same problem

**Comment by dhreben** [comment]
**Steps to upgrade  community branch plugin 1.6.0**

1.Git clone from develop branch
2.Create folders  /opt/sonarqube/extensions/plugins/  and /opt/sonarqube/lib/common/ 
3.copy sonarqube-community-branch-plugin-1.6.0.jar to this paths
4.`cp sonarqube-community-branch-plugin-1.6.0.jar /zebrunner/sonarqube/`
5.`cd zebrunner/sonarqube/`
6.`nano Dockerfile` and change old version  to 8.5-community
7.`nano docker-compose.yml`
8.Enter image: "sonarqube:8.5-community"
9.After the volumes, enter these paths:
   ```
 - /home/ec2-user/tools/zebrunner/sonarqube/sonarqube-community-branch-plugin-1.6.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.6.0.jar
   - /home/ec2-user/tools/zebrunner/sonarqube/sonarqube-community-branch-plugin-1.6.0.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.6.0.jar
```
10.`/zebrunner.sh setup`
11.Open ec2 insane link  http://......./sonarqube/admin/marketplace?filter=installed  and check that community branch plugin 1.6.0 was installed.

**Comment by ghost** [comment]
Verified on develop branch. Plugin is not installed in Sonar.

**Comment by vdelendik** [comment]
done. in order to fix provided relative path for plugins folder and removed old 1.3.2 plugin: https://github.com/zebrunner/sonarqube/commit/67cd12e553a271fdaca7d36f364332fc4fd72053

I'm going to test extra task just to test how upgrade should be applied for sonarqube. Potentially it might include destroy of everything from previous versions :(

**Comment by ghost** [comment]
Plugin is updated on sonar, but after upgrade sonar is not started.
This ticket is done.
