### ISSUE TITLE
migrate to the latest community edition version

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#34]
1. we have to migrate to the latest community 8.5+ version
2. it should use production ready independent postgres container
3. investigate possibility to upgrade but looks like it is impossible based on sonar docs for CE versions
Draft implementation: https://github.com/zebrunner/sonarqube/pull/32

**Comment by vdelendik** [comment]
done. @okamara - clone and setup from scratch using develop branch. and most interesting how static code analysis and PR checker will work as we jumped to 9.9.0-community sonarqube and 1.14.0 community branch plugin:
https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/tag/1.14.0

**Comment by ghost** [comment]
Verified, that sonar is working, code analysis is working, but pr decoration looks like not working. I close this ticket and create a new for pr checker decoration.
https://github.com/zebrunner/sonarqube/issues/43

**Comment by vdelendik** [comment]
reopened and resolved again as we bump up to 9.8 community edition. this time on push and on pull request should work

**Comment by ghost** [comment]
verified, fixed.
