### ISSUE TITLE
onPush job is failed during register repo vs non default/standard branch name

### ISSUE THREAD

**Issue by ghost** [zebrunner/sonarqube#35]
In test branch carina-demo change custom suite api.xml file with such param:
```
<parameter name="jenkinsConcurrentBuild" value="false"/>
```
Register repo with test branch
Actual result: onPush job is failed during register repo 
`20:01:25  [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project carina-demo: No branches currently exist in this project. Please scan the main branch without passing any branch parameters. -> [Help 1]
20:01:25  [ERROR] 
20:01:25  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
20:01:25  [ERROR] Re-run Maven using the -X switch to enable full debug logging.`
[consoleText.txt](https://github.com/zebrunner/pipeline-ce/files/11031593/consoleText.txt)

**Comment by vdelendik** [comment]
fixed using 9.5.0 sonarqube and 1.12.0 community branch plugin.
it has sense during verification right after setup register repository using non default master branch.
also it would be great to use any testng repo where `main`  is default branch to confirm it works too

**Comment by ghost** [comment]
verified, fixed.
