### ISSUE TITLE
Downgrade  Sonarqube version from 9.9.0 to 9.5.0-community edition

### ISSUE THREAD

**Issue by dhreben** [zebrunner/sonarqube#38]
sobj.

**Comment by vdelendik** [comment]
done, `docker build . -t public.ecr.aws/zebrunner/sonarqube:1.4-beta2` is pushed and registered into the CE, branch: develop

**Comment by ghost** [comment]
Sonarqube is not started with version 9.5
<img width="1439" alt="Снимок экрана 2023-04-06 в 13 58 25" src="https://user-images.githubusercontent.com/32964663/230357955-b54e432f-a1b1-473e-8b33-01cd259ec206.png">

2023.04.06 10:51:54 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 9.5.0.56709 / 3185a5669fdfaf7e4fa6dc7876e0b0dfd5d2aae7
2023.04.06 10:51:55 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Starting embedded database on port 9092 with url jdbc:h2:tcp://127.0.0.1:9092/sonar;NON_KEYWORDS=VALUE
2023.04.06 10:51:55 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database started. Data stored in: /opt/sonarqube/data
2023.04.06 10:51:55 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:h2:tcp://127.0.0.1:9092/sonar;NON_KEYWORDS=VALUE
2023.04.06 10:51:55 WARN  web[][o.s.db.dialect.H2] H2 database should be used for evaluation purpose only.
2023.04.06 10:51:57 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
2023.04.06 10:51:57 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2023.04.06 10:51:57 WARN  web[][o.s.c.a.AnnotationConfigApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc-org.sonar.server.plugins.ServerPluginManager': Initialization of bean failed; nested exception is Plugin Community Branch Plugin [communityBranchPlugin] requires at least SonarQube 9.8.0.63668

**Comment by ghost** [comment]
reverified, fixed.
