### ISSUE TITLE
need 2.2-jdk11 sonarqube image

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#4]
Subj

**Comment by vdelendik** [comment]
merged: https://github.com/qaprosoft/sonarqube/pull/5
we decided to keep only one image which can analyze java 8 and java 11 both togheter.
testing can be done with image
qaprosoft/sonarqube:2.2-beta1

**Comment by vdelendik** [comment]
@sandinosanchez, please try to test as is for our carina-demo project sources

**Comment by ghost** [comment]
Tested. Fixed.
