### ISSUE TITLE
revert: disable force authentication on first successful start 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#40]
after upgrading to 9.5.0 sonar in #39 we have force authentication enabled by default.
as CE is fully open source from scratch we have to disable authentication during first successful startup and document later howto enable if needed

**Comment by vdelendik** [comment]
done. after initial setup it suppose to be opened for everybody.
make sure to wait while state of sonarqube docker container is `healthy`.

as designed we can register org and carina-demo repo successfully with full static code analysis.

to disable access for everybody let's provide steps in documentation (separate ticket)

**Comment by ghost** [comment]
Verified that after set up container is started and healthy, 
registered org and carina-demo repo successfully

**Comment by vdelendik** [comment]
reopening to change behavior and make by default fully private

**Comment by vdelendik** [comment]
done. after setup CE from develop branch we have fully private sonarqube, i.e. without login nothing is displayed anymore

**Comment by ghost** [comment]
verified, fixed.
