### ISSUE TITLE
document howto enable force auth and make sonar fully private

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#41]
in scope of #40 we opened it by default to make behavior more open like open-source toolset.
but let's add info in documentation howto close public access and adjust sonar scanner accordingly to use token if necessary etc

**Comment by vdelendik** [comment]
done in scope of community-edition repo. still in TODO new screenshots

**Comment by ghost** [comment]
verified, fixed. nee reverify after release on prod.
