### ISSUE TITLE
reset docker images numbering starting from 1.0

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#8]
Sync with zebrunner team about features, snapshots and release numbers for this repo.
Rename also current 2.3 milestone to 1.0 to start from scratch inside new org

**Comment by vdelendik** [comment]
pushed manually zebrunner/sonarqube:1.0 docker image

**Comment by vdelendik** [comment]
updated docker-compose.yml to use new zebrunner organization image: https://github.com/zebrunner/sonarqube/commit/dcc08fa84f03a19067677a63b66626e2a8a6c4a3

**Comment by ghost** [comment]
Tested on qps-infra develop. Fixed.
