### ISSUE TITLE
provide common zebrunner.sh shell script to manipulate sonar instance

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/sonarqube#9]
need zebrunner.sh script which should support
- start
- stop
- restart?
- down
- shutdown
- backup
- restore

Also script should be smart enough to disable any action if ".disabled" file exists

**Comment by vdelendik** [comment]
start/stop/down/shutdown and backup functionlity finished:
https://github.com/zebrunner/sonarqube/commit/b9f3568cfbba8a2b3d3eb34353e4cad07ad32a8a

**Comment by vdelendik** [comment]
done. make sure to test all kind of actions and negative cases for start/stop/down etc

**Comment by ghost** [comment]
Tested on qps-infra develop, backup/restore issue described in separate ticket.
